<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Choe Nge Valentine Bayni?</title>
  <style>
    body {
      font-family: 'Arial', sans-serif;
      text-align: center;
      background: linear-gradient(135deg, #ff9a9e, #fad0c4);
      margin: 0;
      padding: 0;
      height: 100vh;
      display: flex;
      justify-content: center;
      align-items: center;
      overflow: hidden;
    }
    .container {
      background: white;
      padding: 40px;
      border-radius: 15px;
      box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
      max-width: 400px;
      width: 100%;
    }
    h1 {
      color: #ff6f61;
      font-size: 28px;
      margin-bottom: 20px;
    }
    .buttons {
      display: flex;
      justify-content: center;
      gap: 15px;
    }
    button {
      padding: 15px 30px;
      font-size: 18px;
      border: none;
      border-radius: 10px;
      cursor: pointer;
      transition: transform 0.2s ease, background-color 0.3s ease;
    }
    #yesButton {
      background-color: #4caf50;
      color: white;
    }
    #noButton {
      background-color: #ff6f61;
      color: white;
      transition: all 0.5s ease;
    }
    #noButton:hover {
      background-color: #ff4a3d;
    }
    #yesButton:active, #noButton:active {
      transform: scale(0.95);
    }
    .popup {
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      background: white;
      padding: 30px;
      border-radius: 15px;
      box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
      font-size: 24px;
      color: #ff6f61;
      display: none;
      text-align: center;
      animation: fadeIn 0.5s ease-in-out;
    }
    @keyframes fadeIn {
      from { opacity: 0; transform: translate(-50%, -60%); }
      to { opacity: 1; transform: translate(-50%, -50%); }
    }
  </style>
</head>
<body>
  <div class="container" id="mainContainer">
    <h1>Choe Nge Valentine Bayni ya?</h1>
    <div class="buttons">
      <button id="yesButton">Yes</button>
      <button id="noButton">No</button>
    </div>
  </div>
  <div class="popup" id="popup"></div>

  <script>
    const yesButton = document.getElementById('yesButton');
    const noButton = document.getElementById('noButton');
    const mainContainer = document.getElementById('mainContainer');
    const popup = document.getElementById('popup');

    const excuses = [
      "Den dara ena?",
      "No lab si",
      "Noksam layshom bay tang sa",
      "Last chance!",
      "teru Me sui",
      "expendature gara choe bayni ya?",
      "Howri Kura na gar woi?",
      "Sachi?",
      "Muchu?",
      "No pen cho ani",
      "Ahh Teru thur bu mawa an!",
      "Goodnight",
      "Awa lab",
      "Khe zai",
      "awooooooooooooooo",
    ];

    let clickCount = 0;

    yesButton.addEventListener('click', () => {
      if (clickCount < excuses.length) {
        yesButton.textContent = excuses[clickCount];
        clickCount++;
      } else {
        yesButton.textContent = "Awoooooooo, Teru me sa, tub tub but your paying for everthin!";
        noButton.textContent = "Ok gara nga bew expendature";
      }
    });

    noButton.addEventListener('click', () => {
      if (noButton.textContent === "Ok gara nga bew expendature") {
        mainContainer.style.display = "none";
        popup.textContent = "Yaya! If that's the case, I accept! 🎉💖";
        popup.style.display = "block";
      } else {
        mainContainer.style.display = "none";
        popup.textContent = "Kadrinchoe for saying 'No' and saving me money on Valentine's Day! 💸 Teru Me sa Tik tee mae. 😂";
        popup.style.display = "block";
      }
    });
  </script>
</body>
</html>
